/**
 * Build output is generated by `nx run api:build`. This declaration avoids
 * "module not found" in the editor when dist/ does not exist yet.
 */
declare module '../../dist/apps/api/src/main.js' {
  export function buildApp(): unknown
}
